### ISSUE TITLE
Creating failover ALIAS record broken

### ISSUE THREAD

**Issue by barnybug** [barnybug/cli53#110]
$ cli53 rrcreate example.com test ALIAS 'XYZ example.com.' -i Identifier --failover PRIMARY
Traceback (most recent call last):
  File ".../anaconda/envs/cli53/bin/cli53", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File ".../git/cli53/scripts/cli53", line 10, in <module>
    main()
  File ".../git/cli53/cli53/client.py", line 1111, in main
    args.func(args, r53=connection)
  File ".../git/cli53/cli53/client.py", line 892, in cmd_rrcreate
    for xml in parts:
  File ".../git/cli53/cli53/client.py", line 359, in _xml_changes
    yield self._batch_change(zone, page)
  File ".../git/cli53/cli53/client.py", line 400, in _batch_change
    rdtype.alias_hosted_zone_id)
AttributeError: 'A' object has no attribute 'alias_hosted_zone_id'

ALIAS support generally seems a bit broken - it conflates the type of the record (A, CNAME) with the fact it's an alias - AWS treats them separately, so cli53 should too.

**Comment by barnybug** [comment]
Fixed with new version.
