### ISSUE TITLE
error while importing

### ISSUE THREAD

**Issue by mono-ped** [barnybug/cli53#115]
Traceback (most recent call last):
  File "/usr/local/bin/cli53", line 10, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/cli53/client.py", line 1107, in main
    args.func(args, r53=connection)
  File "/usr/local/lib/python2.7/dist-packages/cli53/client.py", line 609, in cmd_import
    file_parse(args.file)
  File "/usr/local/lib/python2.7/dist-packages/cli53/client.py", line 599, in file_parse
    for line in zonefile:
TypeError: 'NoneType' object is not iterable

I get this error while trying to import.

It's the same on the windows machine I've been using cli53 on daily, and on the fresh ubuntu i just installed to test.

cli53 info works fine.

I've changed nothing and suddently I can't import. Please help!

**Comment by barnybug** [comment]
Please could you try the latest version 0.6.2. The older version didn't
support the AWS extensions well.

**Comment by mono-ped** [comment]
Solved.

Took me a while to figure out I had to update the credentials, but i got there in the end.

Thank-you for the quick reply, and even more for the excellent tool!
