### ISSUE TITLE
Install cli53 using pip

### ISSUE THREAD

**Issue by luisdalves** [barnybug/cli53#130]
Hello,

I'm  trying to install cli53 using pip and appears to be no avaailable:

```
cat /root/.pip/pip.log
------------------------------------------------------------
/usr/bin/pip run on Fri Dec 11 18:23:58 2015
Downloading/unpacking cli53
  Getting page https://pypi.python.org/simple/cli53/
  Could not fetch URL https://pypi.python.org/simple/cli53/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/cli53/ when looking for download links for cli53
  Getting page https://pypi.python.org/simple/
  Real name of requirement cli53 is cli53
  URLs to search for versions for cli53:
  * https://pypi.python.org/simple/cli53/
  Getting page https://pypi.python.org/simple/cli53/
  Could not fetch URL https://pypi.python.org/simple/cli53/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/cli53/ when looking for download links for cli53
  Could not find any downloads that satisfy the requirement cli53
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
No distributions at all found for cli53
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for cli53
```

Is there any way to install it from another repo using pip?

Thanks

**Comment by barnybug** [comment]
It's a single self-contained executable you just need to download now, steps here:
https://github.com/barnybug/cli53/#installation
