### ISSUE TITLE
panic: runtime error running cli53 instances

### ISSUE THREAD

**Issue by jbeaulac** [barnybug/cli53#224]
### Issue type
 - Bug report

### cli53 version (cli53 --version)
0.8.8
### OS / Platform
Ubuntu 14 
### Steps to reproduce
```
wget https://github.com/barnybug/cli53/releases/download/0.8.8/cli53-linux-amd64
sudo mv cli53-linux-amd64 /usr/local/bin/cli53
sudo chmod 0755 /usr/local/bin/cli53
cli53 instances --profile alpha --region us-west-2 -a -n domain.com
```
### Expected behaviour
Output a list of changes that would be made

### Actual behaviour

It appears to manifest with the combination of `--dry-run` and `instances`

```
Getting DNS records
Dry-run, upserts that would be made:
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4702dc]

goroutine 1 [running]:
panic(0x933ba0, 0xc420010090)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/barnybug/cli53/vendor/github.com/urfave/cli.HandleAction.func1(0xc420154cc0)
	/home/travis/gopath/src/github.com/barnybug/cli53/vendor/github.com/urfave/cli/app.go:478 +0x247
panic(0x933ba0, 0xc420010090)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:458 +0x243
github.com/barnybug/cli53.instances(0x7ffd0167581a, 0xe, 0x0, 0x0, 0xc420011d70, 0x1, 0x1, 0x0, 0x3c, 0x0, ...)
	/home/travis/gopath/src/github.com/barnybug/cli53/instances.go:140 +0xf7c
github.com/barnybug/cli53.Main.func6(0xc42007d900, 0x0, 0x0)
	/home/travis/gopath/src/github.com/barnybug/cli53/main.go:224 +0x462
reflect.Value.call(0x905ba0, 0xa34388, 0x13, 0x9e8c6d, 0x4, 0xc420154c80, 0x1, 0x1, 0x5af608, 0x9dbec0, ...)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x905ba0, 0xa34388, 0x13, 0xc420154c80, 0x1, 0x1, 0x9ea3ac, 0xc420046c80, 0x5b8386)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/reflect/value.go:302 +0xa4
github.com/barnybug/cli53/vendor/github.com/urfave/cli.HandleAction(0x905ba0, 0xa34388, 0xc42007d900, 0x0, 0x0)
	/home/travis/gopath/src/github.com/barnybug/cli53/vendor/github.com/urfave/cli/app.go:487 +0x1e0
github.com/barnybug/cli53/vendor/github.com/urfave/cli.Command.Run(0x9eb2ae, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa033c8, 0x33, 0x0, ...)
	/home/travis/gopath/src/github.com/barnybug/cli53/vendor/github.com/urfave/cli/command.go:186 +0xc2b
github.com/barnybug/cli53/vendor/github.com/urfave/cli.(*App).Run(0xc420088180, 0xc42000c090, 0x9, 0x9, 0x0, 0x0)
	/home/travis/gopath/src/github.com/barnybug/cli53/vendor/github.com/urfave/cli/app.go:240 +0x611
github.com/barnybug/cli53.Main(0xc42000c090, 0x9, 0x9, 0xc420000340)
	/home/travis/gopath/src/github.com/barnybug/cli53/main.go:426 +0x2751
main.main()
	/home/travis/gopath/src/github.com/barnybug/cli53/cmd/cli53/main.go:10 +0x45
```

### Have you checked if the documentation has the information you require?
yes
### Could you contribute a fix or help testing with this issue?
Unknown

**Comment by jbeaulac** [comment]
The zone in question has ~800 entries if that helps at all

**Comment by barnybug** [comment]
Sorry, but I couldn't reproduce this in the latest release.
Please re-open this issue if it still occurs, including full commands and/or bind files that demonstrate the issue.
