### ISSUE TITLE
Not pip-installable

### ISSUE THREAD

**Issue by brainstorm** [barnybug/cli53#260]
```python
$ pip install cli53
Collecting cli53
  Downloading https://files.pythonhosted.org/packages/ca/3d/2002bc3467938ca2c5f832592cceb98270eb8c6857966473c74a9a3895a8/cli53-0.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/wz/__dd9trs0kl4jb3rs83704y80000gn/T/pip-install-3he53oky/cli53/setup.py", line 5, in <module>
        long_description = file('README.markdown', 'r').read()
    NameError: name 'file' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wz/__dd9trs0kl4jb3rs83704y80000gn/T/pip-install-3he53oky/cli53/
```

**Comment by barnybug** [comment]
I don't support the python version any more (it's over 3 years out of date!):
https://github.com/barnybug/cli53#wheres-pythonpypi-cli53
