### ISSUE TITLE
Barfs on export if CNAME contains wildcard

### ISSUE THREAD

**Issue by c240amg** [barnybug/cli53#72]
pspencer@phils-mbp-2:~/git/cli53/scripts$ ./cli53 export --full domain.com

_.ivillage.domain.com. 3600 IN CNAME ny1-g007.domain.com
Traceback (most recent call last):
  File "./cli53", line 965, in <module>
    main()
  File "./cli53", line 960, in main
    args.func(args)
  File "./cli53", line 627, in cmd_export
    zone.to_file(sys.stdout, relativize=not args.full)
  File "/Library/Python/2.7/site-packages/dns/zone.py", line 499, in to_file
    relativize=relativize)
  File "/Library/Python/2.7/site-packages/dns/node.py", line 53, in to_text
    print >> s, rds.to_text(name, *_kw)
  File "/Library/Python/2.7/site-packages/dns/rdataset.py", line 214, in to_text
    rd.to_text(origin=origin, relativize=relativize, **kw))
AttributeError: 'NoneType' object has no attribute 'to_text'

**Comment by coffeecoco** [comment]
raceback (most recent call last):
  File "/usr/bin/cli53", line 5, in <module>
    pkg_resources.run_script('cli53==0.4.3', 'cli53')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/cli53-0.4.3-py2.6.egg/EGG-INFO/scripts/cli53", line 976, in <module>
    main()
  File "/usr/lib/python2.6/site-packages/cli53-0.4.3-py2.6.egg/EGG-INFO/scripts/cli53", line 971, in main
    args.func(args)
  File "/usr/lib/python2.6/site-packages/cli53-0.4.3-py2.6.egg/EGG-INFO/scripts/cli53", line 630, in cmd_export
    zone.to_file(sys.stdout, relativize=not args.full)
  File "/usr/lib/python2.6/site-packages/dns/zone.py", line 503, in to_file
    relativize=relativize)
  File "/usr/lib/python2.6/site-packages/dns/node.py", line 53, in to_text
    print >> s, rds.to_text(name, **kw)
  File "/usr/lib/python2.6/site-packages/dns/rdataset.py", line 214, in to_text
    rd.to_text(origin=origin, relativize=relativize, **kw))
AttributeError: 'NoneType' object has no attribute 'to_text'

**Comment by barnybug** [comment]
Could you produce a minimal set of steps on a new (just created) domain to reproduce?
Don't worry - so long as you delete the domain within a 15 mins amazon doesn't charge you anything.

thanks, Barnaby
