### ISSUE TITLE
Exports fail on zones with failover records

### ISSUE THREAD

**Issue by jpreboot** [barnybug/cli53#82]
When I try to export a zone (cli53 export zonename.com) with failover records in it, it stops exporting on the record before the failover and bombs out with this error:

Traceback (most recent call last):
  File "/usr/local/bin/cli53", line 976, in <module>
    main()
  File "/usr/local/bin/cli53", line 971, in main
    args.func(args)
  File "/usr/local/bin/cli53", line 630, in cmd_export
    zone.to_file(sys.stdout, relativize=not args.full)
  File "/usr/local/lib/python2.7/dist-packages/dns/zone.py", line 499, in to_file
    relativize=relativize)
  File "/usr/local/lib/python2.7/dist-packages/dns/node.py", line 53, in to_text
    print >> s, rds.to_text(name, **kw)
  File "/usr/local/lib/python2.7/dist-packages/dns/rdataset.py", line 214, in to_text
    rd.to_text(origin=origin, relativize=relativize, **kw))
AttributeError: 'NoneType' object has no attribute 'to_text'

I believe I have the most current version of the script (updated today). Is there a fix for this? Am I doing something wrong on my end?

**Comment by bhcopeland** [comment]
I am running version 0.5.0 and still get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/cli53", line 10, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/cli53/client.py", line 1103, in main
    args.func(args, r53=connection)
  File "/usr/local/lib/python2.7/dist-packages/cli53/client.py", line 670, in cmd_export
    zone.to_file(sys.stdout, relativize=not args.full)
  File "/usr/lib/python2.7/dist-packages/dns/zone.py", line 499, in to_file
    relativize=relativize)
  File "/usr/lib/python2.7/dist-packages/dns/node.py", line 53, in to_text
    print >> s, rds.to_text(name, **kw)
  File "/usr/lib/python2.7/dist-packages/dns/rdataset.py", line 214, in to_text
    rd.to_text(origin=origin, relativize=relativize, **kw))
AttributeError: 'NoneType' object has no attribute 'to_text'
```

**Comment by barnybug** [comment]
Could someone provide a reproduction case - ie the exact parameters of the record that cause the failure? Thanks

**Comment by bhcopeland** [comment]
So I just had a look at the record that was causing the issue and it was a geolocation record (with health check).

I removed the geolocation record, and now cli53 exports okay... So it wasn't to do with failover, but geolocation.

**Comment by barnybug** [comment]
ah ok - covered by #98

**Comment by barnybug** [comment]
I'll close this issue
