### ISSUE TITLE
Exporting a zone with 188 records fails

### ISSUE THREAD

**Issue by jamengual** [barnybug/cli53#83]
Hi.

We have a big zone that are we trying to export using :
cli53 -d export --full example.com > example.com

but we get this traceback :

Traceback (most recent call last):
  File "/usr/local/bin/cli53", line 976, in <module>
    main()
  File "/usr/local/bin/cli53", line 971, in main
    args.func(args)
  File "/usr/local/bin/cli53", line 628, in cmd_export
    zone = _get_records(args)
  File "/usr/local/bin/cli53", line 625, in _get_records
    return f.get_all_rrsets(r53, info.GetHostedZoneResponse, args.zone)
  File "/usr/local/bin/cli53", line 432, in get_all_rrsets
    return self.convert(ghz, rrsets)
  File "/usr/local/bin/cli53", line 456, in convert
    rrset.identifier, getattr(rrset, 'region', None))
  File "/usr/local/bin/cli53", line 482, in _create_rdataset
    value)
  File "/usr/lib/python2.7/dist-packages/dns/rdtypes/IN/A.py", line 32, in __init__
    junk = dns.ipv4.inet_aton(address)
  File "/usr/lib/python2.7/dist-packages/dns/ipv4.py", line 43, in inet_aton
    raise dns.exception.SyntaxError
dns.exception.SyntaxError

Amazon restriction is 100 updates so it should work with 100+ reads I will think?

Thanks.

**Comment by barnybug** [comment]
This looks like a parse error with the zone file, not related to number of records - perhaps produce a minimal reproduction case and post that in an issue?
