### ISSUE TITLE
Purging zone fails for Weighted Alias records

### ISSUE THREAD

**Issue by pchaganti** [barnybug/cli53#84]
Purging a zone with rrpurge option fails if the zone contains a weighted alias record.

```Python
Traceback (most recent call last):
  File "/usr/local/bin/cli53", line 5, in <module>
    pkg_resources.run_script('cli53==0.4.3', 'cli53')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 489, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1214, in run_script
    exec script_code in namespace, namespace
  File "/Library/Python/2.7/site-packages/cli53-0.4.3-py2.7.egg/EGG-INFO/scripts/cli53", line 1003, in <module>

  File "/Library/Python/2.7/site-packages/cli53-0.4.3-py2.7.egg/EGG-INFO/scripts/cli53", line 998, in main

  File "/Library/Python/2.7/site-packages/cli53-0.4.3-py2.7.egg/EGG-INFO/scripts/cli53", line 887, in cmd_rrpurge

  File "/Library/Python/2.7/site-packages/boto-2.31.1-py2.7.egg/boto/route53/connection.py", line 424, in change_rrsets
    body)
boto.route53.exception.DNSServerError: DNSServerError: 400 Bad Request

<?xml version="1.0"?>
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/">
<Error><Type>Sender</Type>
<Code>InvalidChangeBatch</Code>
<Message>Tried to delete resource record set [name='ui.myz.us.', type='A', set-identifier='weighted alias'] but the values provided do not match the current values</Message>
</Error>
</ErrorResponse>

```

**Comment by barnybug** [comment]
Fixed with new version.
