### ISSUE TITLE
Export fails if record uses geolocation policy

### ISSUE THREAD

**Issue by stevie-** [barnybug/cli53#98]
We use master checkout of cli53.
```
-e git+git@github.com:barnybug/cli53.git@0749aa103bc002bc141027bedba65f60274f115d#egg=cli53-dev
```
Export runs until it hits an A record with routing policy "geolocation" set.
Debug print statement of records
```
<Record:geoloc.DOMAIN.net.:A:IP.ADD.RE.SS>,
<Record:geoloc.DOMAIN.net.:A:ALIAS HOSTEDZONEID dualstack.ssl-termination-ID.eu-central-1.elb.amazonaws.com. (EvalTarget True)>,
```
The first record is for location default and second is for location EUROPE
```
Traceback (most recent call last):
  File "/usr/local/bin/cli53", line 7, in <module>
    execfile(__file__)
  File "/usr/local/lib/python2.7/dist-packages/cli53/src/cli53/scripts/cli53", line 10, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/cli53/src/cli53/cli53/client.py", line 1084, in main
    args.func(args, r53=connection)
  File "/usr/local/lib/python2.7/dist-packages/cli53/src/cli53/cli53/client.py", line 674, in cmd_export
    zone.to_file(sys.stdout, relativize=not args.full)
  File "/usr/local/lib/python2.7/dist-packages/dns/zone.py", line 503, in to_file
    relativize=relativize)
  File "/usr/local/lib/python2.7/dist-packages/dns/node.py", line 53, in to_text
    print >> s, rds.to_text(name, **kw)
  File "/usr/local/lib/python2.7/dist-packages/dns/rdataset.py", line 214, in to_text
    rd.to_text(origin=origin, relativize=relativize, **kw))
AttributeError: 'NoneType' object has no attribute 'to_text'
```

**Comment by stevie-** [comment]
I added print statement for debugging to file ``src/cli53/cli53/client.py`` at the end of function ``def _create_rdataset(rtype, ttl, values, weight, identifier, region, failover):``
```
        else:
            raise ValueError('record type %s not handled' % rtype)
        rdataset.items.append(rdtype)
        print "rtype=",rtype, "ttl=",ttl, "values=",values, "weight=",weight, "identifier=",identifier, "region=", region, "failover=",failover, "rdtype=", rdtype
    return rdataset
```

Result for above entrys
```
rtype= A ttl= 300 values= [u'IP.ADD.RE.SS'] weight= None identifier= Default prd_www region= None failover= None rdtype= None
rtype= ALIAS ttl= 600 values= [u'HOSTEDZONEID dualstack.ssl-termination-ID.eu-central-1.elb.amazonaws.com.'] weight= None identifier= Europe region= None failover= None rdtype= None
```
If ``rdtype``is ``None``it breaks ``rdataset``

**Comment by barnybug** [comment]
Thanks for the report - cli53 has lagged a bit on some of the more exotic/new records Amazon added. Feel free to submit a pull request, or I'll take a look when I get a moment.

**Comment by centminmod** [comment]
funnily i just hit the same problem too

**Comment by barnybug** [comment]
Should be fixed with the new version.
